# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Preparation for build
      run : npm ci
    
    - name: Build 
      run: npm run build
    
    - run: ls -la
    
    - name: Tests
      run: npm test
    
    - run: ls -la ./src
    
    - name: Copy important files
      run: |
        cp ./src/index.html ./
        cp ./src/style.css ./
        cp ./src/arithmetics.js ./
        cp ./dist/scripts.js ./
        
    - run: ls -la 
      
    - name: Build Docker image
      run : docker build -t daniilnedostup/webapp:latest . 
    
    - name: Check image
      run : docker images
    
    - name: Push in DockerHub
      run : |
            docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker tag daniilnedostup/webapp:latest daniilnedostup/webapp:${{ github.sha }}
            docker push daniilnedostup/webapp:latest
            docker push daniilnedostup/webapp:${{ github.sha }}
